# Generated by Django 4.1.1 on 2022-10-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approve_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pending_users',
        ),
        migrations.AddField(
            model_name='event',
            name='event_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='stopping_point',
            field=models.CharField(max_length=50),
        ),
    ]
